### ISSUE TITLE
Invalid URL or Proxy error occurred

### ISSUE THREAD

**Issue by Cuberice** [RenierM26/pyHyypApi#1]
Hi Renier, 

I think there was an update to the App that might cause the login to fail or there is a difference in connection parameters between the ADT version and the IDS version of the App. My IDS App has version 4.1.4 on Android 13

I am attempting to login to the generic version, 
`import json
import pyhyypapi
client = pyhyypapi.HyypClient(email="myEmail",password="myPw",pkg=pyhyypapi.HyypPkg.IDS_HYYP_GENERIC.value)
client.login()`

But get exception
`    client.login()
  File "c:\Development\Source\GITHUB\pyHyypApi\pyhyypapi\client.py", line 72, in login
    raise InvalidURL("A Invalid URL or Proxy error occured") from err
pyhyypapi.exceptions.InvalidURL: A Invalid URL or Proxy error occured`

**Comment by RenierM26** [comment]
Hi @Cuberice,

The "InvalidURL" exception should only raise when there's a connectivity issue. I'm assuming you've checked dns and other network settings?

It calls this url (doesn't matter if it the generic or adt one):
https://ids.trintel.co.za/Inhep-Impl-1.0-SNAPSHOT/auth/login

If you open it in a browser, you should get an invalid login json message.

**Comment by Cuberice** [comment]
Thanks @RenierM26.  
I didn't think it would be blocked by the proxy, but it is working through the VPN.
